-- CreateTable
CREATE TABLE "CRM" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "customerID" TEXT NOT NULL,
    "customerName" TEXT NOT NULL,
    "customerType" TEXT NOT NULL,
    "marketSegment" TEXT NOT NULL,
    "creationDate" DATETIME NOT NULL,
    "lastInteraction" DATETIME NOT NULL,
    "purchaseHistory" TEXT NOT NULL,
    "customerPreferences" TEXT NOT NULL,
    "revenuePotential" TEXT NOT NULL,
    "customerStatus" TEXT NOT NULL,
    "notes" TEXT NOT NULL,
    "associatedCampaigns" TEXT NOT NULL,
    "customerFeedback" TEXT NOT NULL,
    "touchpoints" TEXT NOT NULL,
    "responsibleDepartment" TEXT NOT NULL,
    "customerBirthday" DATETIME NOT NULL,
    "customerRating" TEXT NOT NULL,
    "supportHistory" TEXT NOT NULL,
    "contactNetwork" TEXT NOT NULL,
    "communicationPreferences" TEXT NOT NULL,
    "visitHistory" TEXT NOT NULL,
    "financialSituation" TEXT NOT NULL,
    "customerInterests" TEXT NOT NULL,
    "associatedDocumentation" TEXT NOT NULL,
    "customerLifecycleStage" TEXT NOT NULL,
    CONSTRAINT "CRM_customerID_fkey" FOREIGN KEY ("customerID") REFERENCES "Customer" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
